const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
  SIGNIN_SUCCESS :'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  USER_SIGNOUT_START :'USER_SIGNOUT_START',
  USER_SIGNOUT_SUCCESS :'USER_SIGNOUT_SUCCESS',
  USER_SIGNOUT_FAILURE :'USER_SIGNOUT_FAILURE',
  USER_SIGNUP_START :'USER_SIGNUP_START',
  USER_SIGNUP_SUCCESS :'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAILURE :'USER_SIGNUP_FAILURE'


};

export default UserActionTypes;
